Project_Management/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('mainpage/', views.mainpage),
    path('Project_Management/projectreg/',views.addproject),#url For adding new project
    #path('search/', views.searchoption),#url for search option
    path('Project_Management/list/<id>/',views.attach),# url for pdf attachment
    path('Project_Management/projectdetail/<id>/',views.projectdetail),# url for details
    path('Project_Management/projectlist/',views.projectlist),#url For seeing projectlist
    path('Project_Management/pendingprojectlist/',views.pendingprojectlist),#url For seeing pendingprojectlist
    path('Project_Management/updateproject/<id>/',views.updateproject),#url For updating  project
    path('Project_Management/deleteproject/<id>/',views.deleteproject), #url For delete the project
    path('Project_Management/approvallist/',views.approvallist), #url For delete the project.
    path('Project_Management/approvalpage/<id>/',views.approvalpage), #url For delete the project


    
    path('Project_Management/teamreg/',views.addteam),#url For adding new projectteam
    # path('Project_Management/teamlist/',views.teamlist),#url For adding new projectteamlist
    # path('Project_Management/updateteam/<id>/',views.updateteam),#url For updating  team
    # path('Project_Management/deleteteam/<id>/',views.deleteteam), #url For delete the team

    path('Project_Management/taskreg/',views.addtask),#url For adding new addtask
    path('Project_Management/teamlist/',views.teamlist),#url For adding new projectteamlist
    path("get-assigned-to/", views.get_assigned_to, name="get_assigned_to"),
    path('Project_Management/tasklist/',views.tasklist),#url For seeing projectlist
    # path('Project_Management/updateteam/<id>/',views.updateteam),#url For updating  team
    # path('Project_Management/deleteteam/<id>/',views.deleteteam), #url For delete the team
    path('Project_Management/teammembers/',views.teammembers),
    

    path('Project_Management/Reviewfun/',views.Reviewfun, name= "Reviewfun"),#url for review funciton
    path('Project_Management/Reviewdetail/',views.Reviewdetail),#url for review detail list
    path('',views.home),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('Project_Management.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Project_Management/models.py
from unicodedata import name
from venv import create
from django.db import models



from django.contrib.auth.models import User

from accounts.models import Vertical
# Create your models here.
PROJECT_TASK_STATUS=((0,"Initiated"),(1,"In progress"),(3,"Completed"))
PRIORITY_TYPE=((1,"Low"),(2,"Medium"),(3,"High"))
APPROVAL_STATUS=((1,"Pending"),(2,"Approved"),(3,"Rejected"))
PROJECT_STATUS=((1,"Initiated"),(2,"On going"),(3,"On Hold"),(4,"Completed"))
PROJECT_TYPE=((1,"POC"),(2,"PO"),(3,"ECIF"),(4,"DEMO"),(5,"Initiative"),(6,"Development"))
TASK_TYPE=((1,"Internal Meeting"),(2,"External Meeting"),(3,"Training"),(4,"Task"))

class Project(models.Model):
    project_title=models.CharField(max_length = 100)
    client_Name= models.CharField(max_length = 100, null=True, blank=True)
    creator= models.CharField(max_length = 100)
    
    vertical=models.ForeignKey(Vertical,on_delete=models.CASCADE,blank=True)
    
    CsOwner=models.ForeignKey(User, on_delete=models.CASCADE)
    manager=models.ForeignKey(User, on_delete=models.CASCADE, related_name="project_owner")
    priority=models.IntegerField(choices=PRIORITY_TYPE,default=1,null=True,blank=True)
    project_type=models.IntegerField(choices=PROJECT_TYPE,default=1,null=True,blank=True)
    start_date = models.DateField(null=True,blank=True)
    end_date = models.DateField(null=True,blank=True) 
    remark = models.TextField(null=True, blank=True)
    description=models.TextField(null=True,blank=True)
    approval_status=models.IntegerField(choices=APPROVAL_STATUS,default=1,null=True,blank=True)
    project_status=models.IntegerField(choices=PROJECT_STATUS,default=1,null=True,blank=True)
    attachment = models.FileField(upload_to='media')




    def __str__(self):
        return self.project_title
    
    
class ProjectTeam(models.Model):
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    assign_to= models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    remark=models.TextField(null=True,blank=True)
    attachment = models.FileField(upload_to='media')
     
     
     
     
class Task(models.Model):
    creater=models.CharField(max_length = 100)
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField(auto_now=False, auto_now_add=False)
    task_type=models.IntegerField(choices=TASK_TYPE,default=1,null=True,blank=True)
    task_description=models.TextField(null=True,blank=True)
    Collaborated_with=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    task_status=models.IntegerField(choices=PROJECT_TASK_STATUS,default=1,null=True,blank=True)
    effort_hours=models.IntegerField()
    
class Teammember(models.Model):
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    m1=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    m2=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True,related_name="m2")
    m3=models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True,related_name="m3")
    m4=models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True,related_name="m4")

class Review(models.Model):
    name= models.CharField(max_length = 100)
    comments=models.TextField(max_length=1000)
    rating=models.IntegerField(default=0)

Project_Management/views.py
from xml.etree.ElementTree import Comment
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate, login, logout
from Project_Management.filters import Projectlist,UserFilter
from .models import Project,ProjectTeam,Task,Review
from .forms import Projectform,Taskform,ProjectTeamform,Teammemberform
from django.contrib.auth.models import  User, auth
from django.shortcuts import render,redirect,HttpResponse
from Project_Management.filters import UserFilter
from django.core.mail import EmailMessage, send_mail,EmailMultiAlternatives
from django.conf import settings 
from django.db.models import Q
from django.contrib import messages


# Create your views here.
def mainpage(request):
    data=User.objects.all().count()
    pr=Project.objects.all().count()
    pro=Project.objects.filter(approval_status=1).count()
    user_list =Project.objects.all()
    com=Project.objects.filter(project_status=4).count()
    user_filter = UserFilter(request.GET, queryset=user_list)
    current_user = request.user
    fname = current_user.first_name
    return render(request ,'Projectmanagement/dashboard.html',{'data':data,'pr':pr,'pro':pro,'filter': user_filter,'com':com,'fname':fname})



# def project(request):
    
#     data=Project.objects.filter(active=True)
#     data=data.filter(department=Project.objects.get(user=request.user).department) | data.filter(department= request.user)
    
#     selectedowner=request.GET.get('owner',0)
#     owner = get_user_list(request.user)

#     dept=request.GET.get('department',0)
#     if int(selectedowner):
#         data=data.filter(owner=User.objects.get(id=selectedowner))
#     if int(dept):
#         data=data.filter(department__in=dept)
    

#     department= BusinessType.objects.filter(active=True)

   
#     return render(request,'myadmin/project_management/project.html',{'subuser':owner,'sel3':selectedowner,'data':data,'department':department,'selected_department':int(dept)})



def home(request):
    return render(request ,'base.html')


#----FUNCTIONS RELEATED TO PROJECT-----------#


def addproject(request): #function For adding new project
    current_user = request.user
    ffname = current_user.first_name
    intaial_data ={
        
        'creator': ffname
    }
    
    form=Projectform(initial=intaial_data)
    
    if request.method =='POST':
        
        form=Projectform(request.POST,request.FILES)
        
        if form.is_valid():
            instance = form.save(commit=False)

            vertical_owner = instance.vertical.user.email
            cs_owner = instance.CsOwner.email
            project_owner = instance.manager.email

            Pro= request.POST.get('project_title')
           
            subject = "New Project Created || "+Pro
            body = {
            
			'Project Name': request.POST.get('project_title'), 
			'Client Name': request.POST.get('client_Name'), 
            'Start date': request.POST.get('start_date'),
            'End date':request.POST.get('end_date'), 
            
			}
            content = ("%s: %s" % (key, value) for (key, value) in body.items())
            msg="Dear Team,\n\nNew project has been created.Please find all the details in Project Tracker.\n\nDetails of the Project"
            w="\n\n Waiting for Admin Approval"
            message = msg+ "\n" +"\n" .join(content)+w
            from_email = settings.EMAIL_HOST_USER
            to_list = ['Jegan.rajendran@cloudstrats.com',vertical_owner, cs_owner, project_owner]
            msg = EmailMultiAlternatives(subject, message, from_email, to_list)
            # msg.attach_alternative(html_content, "text/html")
            file_stream = form.cleaned_data['attachment']
            print(f"\n Inmemory Object : {file_stream} \n")
            msg.attach(file_stream.name, file_stream.read(), file_stream.content_type)
            msg.send(fail_silently=True)
            # form.save()
            instance.save()
            
             
        return redirect('/Project_Management/projectreg/')

    return render(request,'Projectmanagement/createproject.html',{'form':form,'ffname':ffname})


def projectlist(request): #function for seeing all project
    data=Project.objects.all()
    uf=Projectlist(request.GET, queryset=data)
    
    return render(request,'Projectmanagement/projectlist.html',{'uf':uf}) 

def pendingprojectlist(request): #function for seeing all project
    data=Project.objects.filter(approval_status=1)
    uf=Projectlist(request.GET, queryset=data)
    
    return render(request,'Projectmanagement/pendingprojectlist.html',{'uf':uf}) 

def updateproject(request,id): #function for updating project details
    product=Project.objects.get(id=id)
    form=Projectform(instance=product)
    if request.method == 'POST':
        form=Projectform(request.POST,request.FILES,instance=product)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/Project_Management/projectlist/')
    file_url = product.attachment.url
    return render(request,'Projectmanagement/updateproject.html',{'form':form, 'file_url':file_url})

def deleteproject(request,id): #function for deleteing project details
    product=Project.objects.get(id=id)
    product.delete()
    return redirect('/Project_Management/projectlist/')

def attach(request,id):
    Doc = Project.objects.get(id=id)
    return render(request,'/list.html',{'i':Doc})

def projectdetail(request,id):
    Doc = Project.objects.get(id=id)
    #Doc=Project(instance=p)
    return render(request,'Projectmanagement/projectdetail.html',{'Doc':Doc})
    # Doc = ""
    # try:
    #     Doc = Project.objects.get(active=True, id=id)
    #     print(Doc)
    # except:
    #     return redirect('/Project_Management/Projectdetail/')
    
    # return render(request,'/Project_Management/projectdetail.html',{'Doc':Doc})

    

def approvallist(request):
    data = Project.objects.exclude(approval_status=2)
    return render(request,'Projectmanagement/approvallist.html',{'data':data})

def approvalpage(request,id): #function for updating project details
    product=Project.objects.get(id=id)
    form=Projectform(instance=product)
    if request.method == 'POST':
        form=Projectform(request.POST,request.FILES,instance=product)
        if form.is_valid():
            instance=form.save(commit=True)
            vertical_owner = instance.vertical.user.email
            cs_owner = instance.CsOwner.email
            project_owner = instance.manager.email

            assgin = instance.manager.first_name
            m="Dear"""+assgin +",\n\n"
            Pro= request.POST.get('project_title')
            p={Pro}
            subject = "Project approved || "+Pro
            # body = {
            
			# 'Project Name': request.POST.get('project_title')
			
			# }
            # content = ("%s: %s" % (key, value) for (key, value) in body.items())
            msg=" project is been approved please assigned team members on PM tracker and initiate the project."
            
            message = m+ "\n" +"\n" .join(p)+msg
            from_email = settings.EMAIL_HOST_USER
            to_list = ['Jegan.rajendran@cloudstrats.com',vertical_owner, cs_owner, project_owner]
            msg = EmailMultiAlternatives(subject, message, from_email, to_list)
            # msg.attach_alternative(html_content, "text/html")
            #file_stream = form.cleaned_data['attachment']
            #print(f"\n Inmemory Object : {file_stream} \n")
            #msg.attach(file_stream.name, file_stream.read(), file_stream.content_type)
            msg.send(fail_silently=True)
            # form.save()
            instance.save()
            return redirect('/Project_Management/approvallist/')
    file_url = product.attachment.url
    return render(request,'Projectmanagement/approvalpage.html',{'form':form, 'file_url':file_url})


# #----FUNCTIONS RELEATED TO PROJECTTEAM-----------#


def addteam(request): #function For adding new projectteam

    form=ProjectTeamform()
    if request.method =='POST':
        form=ProjectTeamform(request.POST,request.FILES)

        if form.is_valid():

            instance=form.save(commit=True)
            assign = instance.assign_to.email
            

            assgin = instance.assign_to.first_name
            m="Dear"""+assgin +",\n\n"
            Pro= instance.project.project_title
            p={Pro}
            subject = "Project Assigned || "+Pro
            # body = {
            
			# 'Project Name': request.POST.get('project_title')
			
			# }
            # content = ("%s: %s" % (key, value) for (key, value) in body.items())
            msg=" project is assigned please executive on PM tracker and initiate the project."
            
            message = m+ "\n" +"\n" .join(p)+msg
            from_email = settings.EMAIL_HOST_USER
            to_list = ['Jegan.rajendran@cloudstrats.com',assign]
            msg = EmailMultiAlternatives(subject, message, from_email, to_list)
            # msg.attach_alternative(html_content, "text/html")
            #file_stream = form.cleaned_data['attachment']
            #print(f"\n Inmemory Object : {file_stream} \n")
            #msg.attach(file_stream.name, file_stream.read(), file_stream.content_type)
            msg.send(fail_silently=True)
            # form.save()
            instance.save()
            return redirect('/mainpage/')

        

    return render(request,'Projectmanagement/createteam.html',{'form':form})

def teamlist(request): #function for seeing all projectteam
    data=ProjectTeam.objects.all()
    
    return render(request,'Projectmanagement/teamlist.html',{'data':data}) 

# def updateteam(request,id): #function for updating team details
#     product=ProjectTeam.objects.get(id=id)
#     form=ProjectTeamform(instance=product)
#     if request.method == 'POST':
#         form=ProjectTeamform(request.POST,request.FILES,instance=product)
#         if form.is_valid():

templates/Projectmanagement/assigned_to.html
<option value="">----------</option>
{% for project in data %}
<option value="{{project.assignted_to.id}}">{{project.assignted_to.first_name}}</option>
{% endfor %}

templates/Projectmanagement/list.html
<!DOCTYPE html>
<html>
  <head>
    <title>list</title>
  </head>
    <body>
       
        {{i.attachment.url }}
     
    </body>
</html>

templates/Projectmanagement/projectdetail.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}
{% block nav %}

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa-solid fa-bars" style="color: #144368; font-size: 1.5rem;"></i>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto" style="margin-top: -7px !important;">

        <li class="nav-link nav-item dropdown px-3">
            <span class="btn p-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"
                style="outline: none;font-weight: 600; color: #144368; font-size: 18px;">
                Project Management
            </span>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% if request.user.is_superuser %}
              <a class="dropdown-item" href="/Project_Management/projectreg">Create Project</a>
              <a class="dropdown-item" href="/Project_Management/projectlist">ProjectList</a>
              <a class="dropdown-item" href="/Project_Management/teamreg">Assign Project</a>
              <a class="dropdown-item" href="/Project_Management/teammembers">Team Allocation</a>
              <a class="dropdown-item" href="/Project_Management/teamlist">TeamList</a>
              <a class="dropdown-item" href="/Project_Management/taskreg">Create Task</a>
              <a class="dropdown-item" href="/Project_Management/tasklist">TaskList</a>
              <a class="dropdown-item" href="/Project_Management/approvallist">Approval</a>
              {% elif request.user.userdetail.userrole == 2 or request.user.userdetail.userrole == 1 or request.user.userdetail.userrole == 5 %}
              <a class="dropdown-item" href="/Project_Management/projectreg">Create Project</a>
              <a class="dropdown-item" href="/Project_Management/projectlist">ProjectList</a>
              <a class="dropdown-item" href="/Project_Management/teamreg">Assign Project</a>
              <a class="dropdown-item" href="/Project_Management/teammembers">Team Allocation</a>
              <a class="dropdown-item" href="/Project_Management/teamlist">TeamList</a>
              <a class="dropdown-item" href="/Project_Management/taskreg">Create Task</a>
              <a class="dropdown-item" href="/Project_Management/tasklist">TaskList</a>
              {% elif request.user.userdetail.userrole == 3 %}
              <a class="dropdown-item" href="/Project_Management/projectreg">Create Project</a>
              <a class="dropdown-item" href="/Project_Management/projectlist">ProjectList</a>
              <a class="dropdown-item" href="/Project_Management/teamreg">Assign Project</a>
              <a class="dropdown-item" href="/Project_Management/teammembers">Team Allocation</a>
              <a class="dropdown-item" href="/Project_Management/teamlist">TeamList</a>
              <a class="dropdown-item" href="/Project_Management/taskreg">Create Task</a>
              <a class="dropdown-item" href="/Project_Management/tasklist">TaskList</a>
              

              {% elif request.user.userdetail.userrole == 4 %}
              <a class="dropdown-item" href="/Project_Management/taskreg">Create Task</a>
              <a class="dropdown-item" href="/Project_Management/projectlist">ProjectList</a>
              <a class="dropdown-item" href="/Project_Management/tasklist">TaskList</a>
              {% elif request.user.userdetail.userrole == 6 %}
                <a class="dropdown-item" href="/Project_Management/projectreg">Create Project</a>
                <a class="dropdown-item" href="/Project_Management/projectlist">ProjectList</a>
                <a class="dropdown-item" href="/Project_Management/teamreg">Assign Project</a>
                <a class="dropdown-item" href="/Project_Management/teammembers">Team Allocation</a>
                <a class="dropdown-item" href="/Project_Management/teamlist">TeamList</a>
                <a class="dropdown-item" href="/Project_Management/taskreg">Create Task</a>
                <a class="dropdown-item" href="/Project_Management/tasklist">TaskList</a>
              {% endif %}
                

                
            </div>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-link nav-item px-3">
            <a href="/Project_Management/Reviewdetail"
                style="text-decoration: none; font-weight: 600; color: #144368; font-size: 18px;">
                See Feedback&nbsp;<i class="fa-solid fa-comments"></i>
            </a>
        </li>
        {% else %}
        <li class="nav-link nav-item px-3">
            <a href="/Project_Management/Reviewfun"
                style="text-decoration: none; font-weight: 600; color: #144368; font-size: 18px;">
                Feedback&nbsp;<i class="fa-solid fa-comments"></i>
            </a>
        </li>
        {% endif %}

        <li class="nav-link nav-item dropdown px-3">
            <span class="btn p-0 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"
                style="outline: none;font-weight: 600; color: #144368; font-size: 18px;">
                <i class="fa-solid fa-user"></i> {{ request.user }}
            </span>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: fit-content;">
              <a class="dropdown-item" href="/accounts/detail/">My Profile</a>
              <a class="dropdown-item" href="/accounts/logout/">Signout</a>
              
            </div>
        </li>
    </ul>
    </nav>


{% endblock %}


{% block body %}
<div class="container text-center">
    <div class="col-md-12 text-center"> 
        <table class="table table-bordered text-center">

        <tr>
            <td><b> Project Title</b></td>
            <td>{{Doc.project_title}}</td>
        </tr>
        <tr>
            <td><b>Client Name</b></td>
            <td>
                
                {{Doc.client_Name}} 
                
            </td>
        </tr>
      
        <tr>
            <td><b>Creater</b></td>
            <td>
                {{Doc.creator}}
                
            </td>
        </tr>
        <tr>
            <td><b>Vertical</b></td>
            <td>
                {{Doc.vertical}}
            </td>
        </tr>
        <tr>
            <td><b>Manager</b></td>
            <td>
                {{Doc.manager}}
            </td>
        </tr>
        <tr>
            <td><b>CsOwner</b></td>
            <td>
                {{Doc.CsOwner}}
            </td>
        </tr>
       
        {% comment %} <tr>
            <td><b>Assigned To</b></td>
            <td>{{Doc.assignted_to}}</td>
        </tr> {% endcomment %}
        <tr>
            <td><b>Priority</b></td>
            
             <td>{{Doc.get_priority_display}}</td>
            
        </tr>
        <tr>
            <td><b>Project Type</b></td>
            
             <td>{{Doc.get_project_type_display}}</td>
            
        </tr>
        <tr>
            <td><b>Start Date</b></td>
            
             <td>{{Doc.start_date}}</td>
            
        </tr>
        <tr>
            <td><b>End Date</b></td>
            
             <td>{{Doc.end_date}}</td>
            
        </tr>
        <tr>
            <td><b>Approval Status</b></td>
            
             <td>{{Doc.get_approval_status_display}}</td>
            
        </tr>
        <tr>
            <td><b>Project Status</b></td>
            
             <td>{{Doc.get_project_status_display}}</td>
            
        </tr>
        
        </table>
        </div>



   

        
   


{% endblock %}